fragment Pagination on Pagination {
	take
	skip
	page
	totalPages
	totalCount
}

fragment Admin on Admin {
	id
	createdAt
	updatedAt
	status
	name
	email
	roleId
	avatar
	avatarUrl
}

fragment AdminRole on AdminRole {
	id
	createdAt
	updatedAt
	status
	name
	description
	code
	permissions
}

fragment Company on Company {
	id
	createdAt
	updatedAt
	status
	name
	alias
	code
	description
	logo
	logoUrl
}

fragment CompanyRole on CompanyRole {
	id
	createdAt
	updatedAt
	status
	name
	description
	code
	permissions
	companyId
}

fragment Member on Member {
	id
	createdAt
	updatedAt
	status
	name
	email
	avatar
	avatarUrl
}


fragment Login on Login {
	target
	accessType
	accessToken
	accessTimeout
}

fragment PermissionItem on PermissionItem {
	name
	subject
	subjectLabel
	group
	action
	actionLabel
	targets
}

fragment PermissionGroupItem on PermissionGroupItem {
	id
	name
	label
	items {
		id
		name
		label
		items {
			id
			name
			label
		}
	}
}

fragment MediaFile on MediaFile {
	id
	createdAt
	updatedAt
	status
	store
	mediaType
	mimeType
	fileName
	fileHash
	fileSize
	width
	height
	duration
	metadata
	description
	extension
	folderId
	owner
	adminId
	memberId
	companyId
	visibility
	url
}