
query PaginateAdminRoles($take: Int, $skip: Int, $where: AdminRoleWhereInput, $orderBy: [AdminRoleOrderByWithRelationInput!]) {
	paginateAdminRoles(take: $take, skip: $skip, where: $where, orderBy: $orderBy) {
		items {
			...AdminRole
		}
		pagination {
			...Pagination
		}
	}
}

query FindOneAdminRole($id: String!) {
	findOneAdminRole(where: { id: $id }) {
		...AdminRole
	}
}

mutation CreateOneAdminRole($data: AdminRoleCreateInput!) {
	createOneAdminRole(data: $data) {
		...AdminRole
	}
}

mutation UpdateOneAdminRole($id: String!, $data: AdminRoleUpdateInput!) {
	updateOneAdminRole(data: $data, where: { id: $id }) {
		...AdminRole
	}
}

query ListAdminRolePermissions {
	listAdminRolePermissions {
		subject
		subjectLabel
		module
		action
		actionLabel
		targets
	}
}

