query Logout {
	logout
}

query Refresh {
	refresh {
		...Login
	}
}

mutation Login($input: LoginInput!) {
	login(input: $input) {
		...Login
	}
}

mutation SwitchAuthCompany($companyId: String!) {
	switchAuthCompany(companyId: $companyId) {
		...Login
	}
}

query ListAuthCompanies($name: String) {
	listAuthCompanies(name: $name) {
		id
		createdAt
		updatedAt
		status
		name
		alias
		code
		description
	}
}


query AuthInfo {
	authInfo {
		id
		createdAt
		updatedAt
		expiredAt
		adminId
		userId
		companyId
		device
		location
		target
	}
}
