
query PaginateCompanies($take: Int, $skip: Int, $where: CompanyWhereInput, $orderBy: [CompanyOrderByWithRelationInput!]) {
	paginateCompanies(take: $take, skip: $skip, where: $where, orderBy: $orderBy) {
		items {
			...Company
		}
		pagination {
			...Pagination
		}
	}
}

query FindOneCompany($id: String!) {
	findOneCompany(where: { id: $id }) {
		...Company
	}
}

mutation CreateOneCompany($data: CompanyCreateInput!) {
	createOneCompany(data: $data) {
		...Company
	}
}

mutation UpdateOneCompany($id: String!, $data: CompanyUpdateInput!) {
	updateOneCompany(data: $data, where: { id: $id }) {
		...Company
	}
}

