
query PaginateCompanyRoles($take: Int, $skip: Int, $where: CompanyRoleWhereInput, $orderBy: [CompanyRoleOrderByWithRelationInput!]) {
	paginateCompanyRoles(take: $take, skip: $skip, where: $where, orderBy: $orderBy) {
		items {
			...CompanyRole
		}
		pagination {
			...Pagination
		}
	}
}

query FindOneCompanyRole($id: String!) {
	findOneCompanyRole(where: { id: $id }) {
		...CompanyRole
	}
}

mutation CreateOneCompanyRole($data: CompanyRoleCreateInput!) {
	createOneCompanyRole(data: $data) {
		...CompanyRole
	}
}

mutation UpdateOneCompanyRole($id: String!, $data: CompanyRoleUpdateInput!) {
	updateOneCompanyRole(data: $data, where: { id: $id }) {
		...CompanyRole
	}
}

query ListCompanyRolePermission {
	listCompanyRolePermission {
		items {
			...PermissionItem
		}
	}
}

