
query PaginateUsers($take: Int, $skip: Int, $where: UserWhereInput, $orderBy: [UserOrderByWithRelationInput!]) {
	paginateUsers(take: $take, skip: $skip, where: $where, orderBy: $orderBy) {
		items {
			...User
		}
		pagination {
			...Pagination
		}
	}
}

query FindOneUser($id: String!) {
	findOneUser(where: { id: $id }) {
		...User
	}
}

mutation CreateOneUser($data: UserCreateInput!) {
	createOneUser(data: $data) {
		...User
	}
}

mutation UpdateOneUser($id: String!, $data: UserUpdateInput!) {
	updateOneUser(data: $data, where: { id: $id }) {
		...User
	}
}

