
query PaginateMembers($take: Int, $skip: Int, $where: MemberWhereInput, $orderBy: [MemberOrderByWithRelationInput!]) {
	paginateMembers(take: $take, skip: $skip, where: $where, orderBy: $orderBy) {
		items {
			...Member
		}
		pagination {
			...Pagination
		}
	}
}

query FindOneMember($id: String!) {
	findOneMember(where: { id: $id }) {
		...Member
	}
}

mutation CreateOneMember($data: MemberCreateInput!) {
	createOneMember(data: $data) {
		...Member
	}
}

mutation UpdateOneMember($id: String!, $data: MemberUpdateInput!) {
	updateOneMember(data: $data, where: { id: $id }) {
		...Member
	}
}

