
query PaginateWebsites($take: Int, $skip: Int, $where: WebsiteWhereInput, $orderBy: [WebsiteOrderByWithRelationInput!]) {
	paginateWebsites(take: $take, skip: $skip, where: $where, orderBy: $orderBy) {
		items {
			...Website
		}
		pagination {
			...Pagination
		}
	}
}



query FindOneWebsite($id: String!) {
	findOneWebsite(where: { id: $id }) {
		...Website
	}
}

mutation CreateOneWebsite($data: WebsiteCreateInput!) {
	createOneWebsite(data: $data) {
		...Website
	}
}

mutation UpdateOneWebsite($id: String!, $data: WebsiteUpdateInput!) {
	updateOneWebsite(data: $data, where: { id: $id }) {
		...Website
	}
}

query ListWebsiteSeoPage($id: String!) {
	listWebsiteSeoPage(where: { id: $id }) {
		apiId
		contentType
		document
		documentId
		documentTitle
		id
		title
		url
		md5
		score
		status
	}
}

mutation PushAllPagesToAnalyze($id: String!) {
	pushAllPagesToAnalyze(where: { id: $id })
}

mutation PushPagesToAnalyze($id: String!, $urls: [String!]!) {
	pushPagesToAnalyze(where: { id: $id }, urls: $urls)
}

mutation PushPagesToUpdate($id: String!, $urls: [String!]!) {
	pushPagesToUpdate(where: { id: $id }, urls: $urls)
}
